on: push
name: Build project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Cloud SDK Pipeline
      uses: SAP/devops-docker-cx-server/jenkinsfile-runner-github-action@master
